Repository AY2324S1-CS2103T-T12-3/tp, pull requests merged in 2023-10, with the labels that each got.

#39 Add assignment model
  src/main/java/seedu/address/logic/commands/assignment/Command.java
  src/main/java/seedu/address/logic/commands/event/Command.java
  src/main/java/seedu/address/logic/commands/internship/Command.java
  src/main/java/seedu/address/logic/parser/assignment/Parser.java
  src/main/java/seedu/address/logic/parser/event/Parser.java
  src/main/java/seedu/address/logic/parser/internship/Parser.java
  src/main/java/seedu/address/model/assignment/Assignment.java
  src/main/java/seedu/address/model/assignment/exceptions/AssignmentNotFoundException.java
  src/main/java/seedu/address/model/assignment/exceptions/DuplicateAssignmentException.java
Labels: priority.High

#60 Add find assignment command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/assignment/FindAssignmentCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/assignment/FindAssignmentCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/assignment/UniqueAssignmentList.java
  src/test/java/seedu/address/logic/commands/assignment/AddAssignmentCommandTest.java
  src/test/java/seedu/address/logic/commands/assignment/FindAssignmentCommandTest.java
Labels: type.Story

#99 Update ug
  docs/UserGuide.md
  docs/images/LabelledGUI.png
Labels: documentation

#98 update-UG-mark-unmark-and-newUserTutorial
  docs/UserGuide.md
  docs/images/NewUserTutAdd1.png
  docs/images/NewUserTutAddMoreAssgn.png
  docs/images/NewUserTutDelete.png
  docs/images/NewUserTutEdit.png
  docs/images/NewUserTutFind.png
  docs/images/NewUserTutList.png
  docs/images/NewUserTutMark.png
  src/main/java/seedu/address/logic/commands/assignment/AddAssignmentCommand.java
Labels: documentation

#100 Update UG
  docs/UserGuide.md
Labels: documentation

#108 Chore: Update DG Storage class diagram
  docs/images/StorageClassDiagram.png
Labels: documentation

#113 Update DG use case and user stories
  docs/DeveloperGuide.md
Labels: documentation

#109 Update UML diagram for Architechture sequence diagram, and Logic sequ…
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
Labels: documentation

#120 Update DG Model component
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
Labels: documentation
